version: "3.9"

services:
  testt:
    image: moheyum/nginx-dev:latest
    ports:
      - "80:80"
      - "443:443"
    deploy:
      mode: global
      update_config:
        delay: 10s
        order: start-first
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt