name: NGINX PR 테스트

on:
  pull_request:
    branches: #target
      - dev
      - main
    paths:
      - "nginx/**"
  workflow_dispatch:

jobs:
  nginx-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build image and test
        run: |
          docker build -t web34-nginx-local:test --target dev ./nginx && docker run --add-host host.docker.internal:host-gateway --rm web34-nginx-local:test nginx -t
